# yaml-language-server: $schema=https://github.com/GoogleContainerTools/skaffold/raw/v2.13.2/docs-v2/content/en/schemas/v3.json
apiVersion: skaffold/v3
kind: Config
build:
  platforms:
  - linux/amd64
  - linux/arm64/v8
  artifacts:
  - image: localdir1
    context: ./test/localdir1
    custom:
      buildCommand: contain -x --file-output ../out/localdir.json
  - image: localdir-app
    context: ./test/localdir-app
    custom:
      buildCommand: contain -x -b mirror.gcr.io/library/busybox@sha256:c3839dd800b9eb7603340509769c43e146a74c63dca3045a8e7dc8ee07e53966 --file-output ../out/localdir-app.json
  - image: localdir-app-dot
    context: ./test/localdir-app
    custom:
      buildCommand: contain -x -b mirror.gcr.io/library/busybox@sha256:c3839dd800b9eb7603340509769c43e146a74c63dca3045a8e7dc8ee07e53966 --file-output ../out/localdir-app-dot.json .
  - image: localdir-app-env
    context: ./test/localdir-app
    custom:
      buildCommand: CONTAIN_BASE=mirror.gcr.io/library/busybox@sha256:c3839dd800b9eb7603340509769c43e146a74c63dca3045a8e7dc8ee07e53966 contain -x --file-output ../out/localdir-app-env.json
  - image: contextdir-app
    context: ./test
    custom:
      buildCommand: contain -x -b mirror.gcr.io/library/busybox@sha256:c3839dd800b9eb7603340509769c43e146a74c63dca3045a8e7dc8ee07e53966 --file-output ./out/contextdir-app.json ./localdir-app
  - image: contextdir-config
    context: test
    custom:
      buildCommand: contain -x localdir1 --file-output out/contextdir-config.json
  - image: localdir-amd64
    context: ./test/localdir-app
    platforms:
    - linux/amd64
    custom:
      buildCommand: contain -x -b mirror.gcr.io/library/busybox@sha256:c3839dd800b9eb7603340509769c43e146a74c63dca3045a8e7dc8ee07e53966 --file-output ../out/localdir-amd64.json
  - image: localdir-arm64
    context: ./test/localdir-app
    platforms:
    - linux/arm64/v8
    custom:
      buildCommand: contain -x -b mirror.gcr.io/library/busybox@sha256:c3839dd800b9eb7603340509769c43e146a74c63dca3045a8e7dc8ee07e53966 --file-output ../out/localdir-arm64.json
  - image: multilayer
    context: ./test/multilayer
    custom:
      buildCommand: contain -x --file-output ../out/mutilayer.json
  - image: symlinks
    context: ./test
    custom:
      buildCommand: contain -x -f symlinks.contain.yaml --file-output out/symlinks.json
  - image: config-override
    context: ./test/localdir1
    custom:
      buildCommand: contain -x -b gcr.io/distroless/base-debian11:debug-nonroot@sha256:3011e1597a9e51812d1c3287403abd44396c5e23d40f661252e2ef468a71aa07 --file-output ../out/config-override.json
  - image: config-stdin
    context: ./test
    custom:
      buildCommand: |-
        cat <<EOF | IMAGE="" contain -x -c - --file-output out/config-stdin.json
        base: gcr.io/distroless/base-debian11:debug-nonroot@sha256:3011e1597a9e51812d1c3287403abd44396c5e23d40f661252e2ef468a71aa07
        tag: $IMAGE
        layers:
        - localDir:
            path: localdir-app
            containerPath: /config-stdin
        EOF
  - image: localdir-streams
    context: ./test/localdir-app
    custom:
      buildCommand: >
        contain -x -b mirror.gcr.io/library/busybox@sha256:c3839dd800b9eb7603340509769c43e146a74c63dca3045a8e7dc8ee07e53966 --file-output ../out/localdir-streams.json
        1> ../example-stdout.out
        2> ../example-stderr.out;
        echo "------ stdout ------"; cat ../example-stdout.out;
        echo "------ stderr ------"; cat ../example-stderr.out;
  - image: filemode
    context: ./test
    custom:
      buildCommand: contain -x -c filemode.contain.yaml --file-output out/filemode.json
  - image: onefile
    context: ./test
    custom:
      buildCommand: contain -x -c onefile.contain.yaml --file-output out/onefile.json

test:
- image: localdir1
  structureTests:
  - ./test/localdir1/test.yaml
- image: localdir-app
  structureTests:
  - ./test/localdir-app-test.yaml
- image: localdir-app-dot
  structureTests:
  - ./test/localdir-app-test.yaml
- image: localdir-app-env
  structureTests:
  - ./test/localdir-app-test.yaml
- image: contextdir-app
  structureTests:
  - ./test/localdir-app-test.yaml
- image: contextdir-config
  structureTests:
  - ./test/localdir1/test.yaml
- image: multilayer
  structureTests:
  - ./test/multilayer/test.yaml
- image: config-override
  structureTests:
  - ./test/config-override-test.yaml
- image: config-stdin
  structureTests:
  - ./test/config-override-test.yaml
- image: filemode
  structureTests:
  - ./test/filemode.test.yaml
- image: onefile
  structureTests:
  - ./test/onefile.test.yaml
